### ISSUE TITLE
Include a readme.html file for help

### ISSUE THREAD

**Issue by nvdaes** [albzan/whiteNoise#1]
I see the following error in the store.

STR:

1. Open NVDA store and select White Noise.
2. Go to actions and press help

ERROR - unhandled exception (12:42:03.398) - MainThread (10800):
Traceback (most recent call last):
  File "gui\_addonStoreGui\controls\actions.pyc", line 37, in _menuItemClicked
  File "gui\_addonStoreGui\viewModels\store.pyc", line 240, in helpAddon
TypeError: startfile: filepath should be string, bytes or os.PathLike, not NoneType

Alternatively, remove the doc filename field in manifest.ini.
Cheers

**Comment by albzan** [comment]
Thank you,

yes I'll remove it since the README does not add any additional information
regarding the addon because it is really easy.
I'll do it in the next days and I'll publish a new release. Probably the
SpeKey addon is afflicted too.


Il giorno dom 30 lug 2023 alle ore 12:43 Noelia Ruiz Martínez <
***@***.***> ha scritto:

**Comment by nvdaes** [comment]
I think that the contents of the readme of the speakKey is better than 
the description. I'd improve the description and, if you think that the 
readme is not useful, you may remove it.
